### ISSUE TITLE
Fix WorkGraph priority callback argument leakage

### ISSUE THREAD

**Issue by jdoe-dev-159753** [jdoe-dev-159753/specgraph-reference-app#80]
## Discovery

The first canonical Project v2 reconciliation run after merging #57 fails on `main` while deriving PR priority.

Observed failure from Actions run `33386599323`:

```text
TypeError: seen.has is not a function
  at effectiveIssuePriority (...project-v2-reconcile.cjs:138:14)
  at Array.map (<anonymous>)
  at module.exports (...project-v2-reconcile.cjs:320:43)
```

## Cause

`effectiveIssuePriority(item, seen = new Set())` is passed directly to `Array.map`:

```js
owningItems.map(effectiveIssuePriority)
```

JavaScript supplies the element index as the callback's second argument, so `seen` becomes a number rather than the recursive `Set` expected by the function.

## Correction

Wrap the call in a unary lambda so only the item is supplied:

```js
owningItems.map(item => effectiveIssuePriority(item))
```

Then rerun the canonical reconciler against the entire Project and verify that priority, disposition and Status reconciliation completes without a runtime exception.

This is an implementation defect in the reconciler, not a change to WorkGraph semantics.
